---
title: "文字云制作，侠客行电子书"
output:
  html_document:
    df_print: paged
---
资料来源：<http://www.zadzs.com/plus/download.php?open=0&aid=271&cid=3>


下载包
```{r}
library(NLP)
library(tm)
library(jiebaRD)
library(jiebaR)
library(RColorBrewer)
library(wordcloud)
library(rvest)
```

從電腦讀檔， 移除可能有問題的符號
```{r}
setwd("C:/Users/goodman/Desktop/")
filenames <- list.files(getwd(), pattern="3599.txt")
files <- lapply(filenames, readLines)
docs <- Corpus(VectorSource(files))
toSpace <- content_transformer(function(x, pattern) {
return (gsub(pattern, "", x))
}

)
```
移除標點符號，移除數字跟空白，
```{r}
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, stripWhitespace)
```
確保任何形式的單字只會轉換成相同詞性出現一次
```{r}
docs <- tm_map(docs, stemDocument)
```
斷詞
```{r}
mixseg = worker()
jieba_tokenizer=function(d){
unlist(segment(d[[1]],mixseg))
}

seg = lapply(docs, jieba_tokenizer)
freqFrame = as.data.frame(table(unlist(seg)))
```

文字云图形制作
```{r}
par(family=("Heiti TC Light"))
wordcloud(freqFrame$Var1,freqFrame$Freq,
scale=c(5,0.1),min.freq=50,max.words=150,
random.order=TRUE, random.color=FALSE,
rot.per=.1, colors=brewer.pal(8, "Dark2"),
ordered.colors=FALSE,use.r.layout=FALSE,
fixed.asp=TRUE)
```

```{r}
mixseg = worker()
jieba_tokenizer=function(d){
  unlist(segment(d[[1]],mixseg))
}
seg = lapply(docs, jieba_tokenizer)
freqFrame = as.data.frame(table(unlist(seg)))
freqFrame = freqFrame[order(freqFrame$Freq,decreasing=TRUE), ]
library(knitr)
kable(head(freqFrame), format = "markdown")
```

