---
title: "goodreads book 網路書籍的評論率調查"
output: html_document
---



```{r}
library(dplyr)
setwd("C:/Users/goodman/Desktop")

book1<-read.csv('book1.csv')
head(book1)

book2<-read.csv('book2.csv')
head(book2)

```

```{r}
  book1$average_rating = as.numeric(as.character(book1$average_rating))
 View(book1)
 as.numeric(as.character(book1))
 book1new<-filter(book1,average_rating>=5)
  book1new<-select(book1new,bookID,title,average_rating,text_reviews_count)
  book1new<-arrange(book1new,desc(text_reviews_count))
  book1new<-head(book1new)
  book1new
 View(book1new)
```
book
```{r}
 book1new2<-select(book1,bookID,title,average_rating,text_reviews_count)
 book1new2<-arrange(book1new2,desc(text_reviews_count))
 book1new2<-head(book1new2)
 book1new2
```

 
```{r}
 book2new<-filter(book2,book_average_rating>=5)
 book2new<-select(book2new,author_id,book_average_rating,book_title,num_reviews)
 book2new<-arrange(book2new,desc(num_reviews))
 book2new<-head(book2new)
 book2new
```
 
```{r}
 book2new2<-select(book2,author_id,book_average_rating,book_title,num_reviews)
 book2new2<-arrange(book2new2,desc(num_reviews))
 book2new2<-head(book2new2)
 book2new2
```

 
 
 
 